### ISSUE TITLE
How can I search without ignoring the license info.

### ISSUE THREAD

**Issue by MainTankJerry** [tuvistavie/bigcode-tools#7]
I am trying to download all Java projects that are related to the keyword " dynamic programming", but the search always returns 0 result. Here is the command I ran:
`bigcode-fetcher search --language Java --keyword 'dynamic programming' --star '>-1' --max-repos 1000 --license all --size 1..1000000 --token XXX -o dynamicprogramming-1000.json`

If I search 'dynamic programming' on github, I can find 687 java projects. All I want is to download all of them. Thank you.

**Comment by tuvistavie** [comment]
Thanks for reporting. Having `all` in license should now completely skip the license checking step. Could you try with the latest version please? I already published to pip.

**Comment by MainTankJerry** [comment]
Thank you so much.
